<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>异常穿透</title>
</head>

<body>
    <script>
        //当使用promise的then链式调用时 可以在最后指定失败的回调
        //前面任何操作出现异常 都会传到最后失败的回调中处理
        let p = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('ok')
            }, 1000);
        })

        p.then(value => {
            console.log(1);
        }).then(value => {
            throw 'Err'
        }).then(value => {
            console.log(3);
        }).catch(reason => {
            console.warn(reason);
        })
    </script>
</body>

</html>